mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.conf.urls import url


from . import views
app_name = "polls"
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url('delete', views.delete, name='delete'),
    # ex: /polls/5/results/
    url('results', views.results, name='results'),
    # ex: /polls/5/vote/
    url('full', views.full, name='full'),
    url('update', views.update, name='update'),

]

polls/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField(max_length=50, default='SOME STRING')
    comment = models.CharField(max_length=200)
    predict = models.CharField(max_length=20)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .model.process import Process

import os
import django
from polls.models import Comment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings");
django.setup()

def index(request):
    context = {
        'latest_question_list': 'lêu lêu',
    }
    return render(request, 'polls/index.html', context)


def delete(request):
    Comment.objects.all().delete()
    return HttpResponse("Deleted")


def results(request):
    context = {
        'name': request.POST['name'],
        'comment': request.POST['comment'],
        'predicted': Process.test(request.POST['comment']),
    }

    c = Comment(name=context['name'], comment=context['comment'], predict=context['predicted'])
    c.save()
    return render(request, 'polls/results.html', context)


def full(request):

    data = []
    for x in Comment.objects.all():
        data.append({
            'id': x.id,
            'name': x.name,
            'comment': x.comment,   
            'predicted': x.predict,
        })
    context = {
        'data': data,
    }
    return render(request, 'polls/thongke.html', context)

def update(request):
    rid = request.GET['rid']
    data = []
    for x in Comment.objects.filter(id__gt=rid):
        data.append({
            'id': x.id,
            'name': x.name,
            'comment': x.comment,   
            'predicted': x.predict,
        })
    context = {
        'data': data,
    }
    return render(request, 'polls/update.html', context)

polls/templates/polls/index.html
<style>
  @import url(
    https://fonts.googleapis.com/css?family=Roboto:400,
    300,
    600,
    400italic
  );
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-font-smoothing: antialiased;
    -o-font-smoothing: antialiased;
    font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }

  body {
    font-family: "Roboto", Helvetica, Arial, sans-serif;
    font-weight: 100;
    font-size: 12px;
    line-height: 30px;
    color: #777;
    background: #4caf50;
  }

  .container {
    max-width: 400px;
    width: 100%;
    margin: 0 auto;
    position: relative;
  }

  #contact input[type="text"],
  #contact input[type="email"],
  #contact input[type="tel"],
  #contact input[type="url"],
  #contact textarea,
  #contact button[type="submit"] {
    font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
  }

  #contact {
    background: #f9f9f9;
    padding: 25px;
    margin: 150px 0;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  }

  #contact h3 {
    display: block;
    font-size: 30px;
    font-weight: 300;
    margin-bottom: 20px;
  }

  #contact h4 {
    margin: 5px 0 15px;
    display: block;
    font-size: 13px;
    font-weight: 400;
  }

  fieldset {
    border: medium none !important;
    margin: 0 0 10px;
    min-width: 100%;
    padding: 0;
    width: 100%;
  }

  #contact input[type="text"],
  #contact input[type="email"],
  #contact input[type="tel"],
  #contact input[type="url"],
  #contact textarea {
    width: 100%;
    border: 1px solid #ccc;
    background: #fff;
    margin: 0 0 5px;
    padding: 10px;
    font-size: 15px;
  }

  #contact input[type="text"]:hover,
  #contact input[type="email"]:hover,
  #contact input[type="tel"]:hover,
  #contact input[type="url"]:hover,
  #contact textarea:hover {
    -webkit-transition: border-color 0.3s ease-in-out;
    -moz-transition: border-color 0.3s ease-in-out;
    transition: border-color 0.3s ease-in-out;
    border: 1px solid #aaa;
  }

  #contact textarea {
    height: 100px;
    max-width: 100%;
    resize: none;
  }

  #contact button[type="submit"] {
    cursor: pointer;
    width: 100%;
    border: none;
    background: #4caf50;
    color: #fff;
    margin: 0 0 5px;
    padding: 10px;
    font-size: 15px;
  }

  #contact button[type="submit"]:hover {
    background: #43a047;
    -webkit-transition: background 0.3s ease-in-out;
    -moz-transition: background 0.3s ease-in-out;
    transition: background-color 0.3s ease-in-out;
  }

  #contact button[type="submit"]:active {
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
  }

  .copyright {
    text-align: center;
  }

  #contact input:focus,
  #contact textarea:focus {
    outline: 0;
    border: 1px solid #aaa;
  }

  ::-webkit-input-placeholder {
    color: #888;
  }

  :-moz-placeholder {
    color: #888;
  }

  ::-moz-placeholder {
    color: #888;
  }

  :-ms-input-placeholder {
    color: #888;
  }
</style>
<body>
  <div class="container">
    <form id="contact" action="{% url 'polls:results' %}" method="post">
        {% csrf_token %}
      <h3 align="center">Post Comment</h3>
      <fieldset>
        <input
          placeholder="Your name"
          name="name"
          type="text"
          tabindex="1"
          required
          autofocus
        />
      </fieldset>
      <fieldset>
        <textarea
          name="comment"
          placeholder="Type your comment here...."
          tabindex="5"
          required
        ></textarea>
      </fieldset>
      <fieldset>
        <button
          name="submit"
          type="submit"
          id="contact-submit"
          data-submit="...Sending"
        >
          Submit
        </button>
      </fieldset>
    </form>
  </div>
</body>

polls/templates/polls/results.html
<style>
  @import url(
    https://fonts.googleapis.com/css?family=Roboto:400,
    300,
    600,
    400italic
  );
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-font-smoothing: antialiased;
    -o-font-smoothing: antialiased;
    font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }

  body {
    font-family: "Roboto", Helvetica, Arial, sans-serif;
    font-weight: 100;
    font-size: 12px;
    line-height: 30px;
    color: #777;
    background: #4caf50;
  }

  .container {
    max-width: 400px;
    width: 100%;
    margin: 0 auto;
    position: relative;
  }

  #contact input[type="text"],
  #contact input[type="email"],
  #contact input[type="tel"],
  #contact input[type="url"],
  #contact textarea,
  #contact button[type="submit"] {
    font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
  }

  #contact {
    background: #f9f9f9;
    padding: 25px;
    margin: 150px 0;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  }

  #contact h3 {
    display: block;
    font-size: 30px;
    font-weight: 300;
    margin-bottom: 20px;
  }

  #contact h4 {
    margin: 5px 0 15px;
    display: block;
    font-size: 13px;
    font-weight: 400;
  }

  fieldset {
    border: medium none !important;
    margin: 0 0 10px;
    min-width: 100%;
    padding: 0;
    width: 100%;
  }

  #contact input[type="text"],
  #contact input[type="email"],
  #contact input[type="tel"],
  #contact input[type="url"],
  #contact textarea {
    width: 100%;
    border: 1px solid #ccc;
    background: #fff;
    margin: 0 0 5px;
    padding: 10px;
    font-size: 15px;
  }

  #contact input[type="text"]:hover,
  #contact input[type="email"]:hover,
  #contact input[type="tel"]:hover,
  #contact input[type="url"]:hover,
  #contact textarea:hover {
    -webkit-transition: border-color 0.3s ease-in-out;
    -moz-transition: border-color 0.3s ease-in-out;
    transition: border-color 0.3s ease-in-out;
    border: 1px solid #aaa;
  }

  #contact textarea {
    height: 100px;
    max-width: 100%;
    resize: none;
  }

  #contact button {
    cursor: pointer;
    width: 100%;
    border: none;
    background: #4caf50;
    color: #fff;
    margin: 0 0 5px;
    padding: 10px;
    font-size: 15px;
  }

  #contact button:hover {
    background: #43a047;
    -webkit-transition: background 0.3s ease-in-out;
    -moz-transition: background 0.3s ease-in-out;
    transition: background-color 0.3s ease-in-out;
  }

  #contact button:active {
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
  }

  .copyright {
    text-align: center;
  }

  #contact input:focus,
  #contact textarea:focus {
    outline: 0;
    border: 1px solid #aaa;
  }

  ::-webkit-input-placeholder {
    color: #888;
  }

  :-moz-placeholder {
    color: #888;
  }

  ::-moz-placeholder {
    color: #888;
  }

  :-ms-input-placeholder {
    color: #888;
  }
</style>
<body>
  <div class="container">
    <form id="contact" action="{% url 'polls:results' %}" method="post">
        {% csrf_token %}
      <h3 align="center">Result</h3>
      <fieldset>
        <input
          value="{{ predicted }}"
          type="text"
          tabindex="1"
          required
          disabled
        />
      </fieldset>
      <fieldset>
        <button action="action" onclick="window.history.go(-1); return false;" type="button" value="Back" >
          Back
        </button>
      </fieldset>
    </form>
  </div>
</body>

polls/templates/polls/thongke.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<title>Table V02</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'polls/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'polls/until.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	<div class="limiter">
		<div class="container-table100">
			<div class="wrap-table100">
					<div class="table">

						<div class="row header">
							<div class="cell">
								Name
							</div>
							<div class="cell">
								Comment
							</div>
							<div class="cell">
								Label
							</div>
						</div>

						{% for x in data %}
						<div class="row" rid="{{x.id}}">
							<div class="cell" data-title="Name">
								{{x.name}}
							</div>
							<div class="cell" data-title="Comment">
								{{x.comment}}
							</div>
							<div class="cell" data-title="Label">
								{{x.predicted}}
							</div>
						</div>
						{% endfor %}

					</div>
			</div>
		</div>
	</div>


	
	<script src="js/main.js"></script>
	<script>
	function startRefresh() {
    $.get('update', {rid:$(".row").last().attr('rid')}, function(data) {
        $('.table').append(data);    
    });
}
$(function() {
    setInterval(startRefresh,3000);
});
	</script>


</body>
</html>

polls/templates/polls/update.html
{% for x in data %}
<div class="row" rid="{{x.id}}">
    <div class="cell" data-title="Name">
        {{x.name}}
    </div>
    <div class="cell" data-title="Comment">
        {{x.comment}}
    </div>
    <div class="cell" data-title="Label">
        {{x.predicted}}
    </div>
</div>
{% endfor %}